version: '3'

services:
  api:
    build: .
    command: /bin/bash  ./test
    volumes:
      - ./:/task5
    expose:
      - 5000
    depends_on:
      - mysql-main
  nginx:
    image: nginx:1.16
    ports:
      - "8000:5000"
    volumes:
      - ./nginx.conf:/etc/conf.d/main.conf
    depends_on:
      - api
  mysql-main:
    container_name: mysql-main
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=day9
      - MYSQL_USER=blase
      - MYSQL_PASSWORD=123
  test-db:
    container_name: test-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=blase
      - MYSQL_PASSWORD=123